name 'mem-consumption'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures mem-consumption'
long_description 'Installs/Configures mem-consumption'
version '0.1.0'

depends 'rsyslog'
depends 'sysctl'
depends 'ark'
depends 'hostsfile'
depends 'selinux'
depends 'ntp'
depends 'sudo'
depends 'git'
depends 'runit'
depends 'apt'
depends 'java'
depends 'apache2'
depends 'nginx'
depends 'yum'
depends 'chef-client'
depends 'firewall'
depends 'users'
depends 'nodejs'
depends 'openssl'
depends 'postfix'
depends 'cron'
depends 'logrotate'
depends 'vim'
depends 'resolver'
depends 'chef-sugar'
